(* Git must inspect the source checkout, not the sandbox's copied build tree.
   The Dune rule reruns this lookup because refs are not source dependencies. *)
let () =
  let source_root =
    match Sys.getenv_opt "DUNE_SOURCEROOT" with
    | Some root -> root
    | None -> Sys.getcwd ()
  in
  let command =
    "git -C " ^ Filename.quote source_root
    ^ " describe --tags --always 2>/dev/null"
  in
  let channel = Unix.open_process_in command in
  let description = try Some (input_line channel) with End_of_file -> None in
  let version =
    match (Unix.close_process_in channel, description) with
    | Unix.WEXITED 0, Some version when version <> "" -> version
    | _ -> "dev"
  in
  Printf.printf "(* Auto-generated by dune — do not edit *)\nlet s = %S\n"
    version
