(* Dune supplies the version explicitly, so sandboxing and build caches cannot
   hide a release tag or reuse another build's version. *)
let () =
  let version = Sys.argv.(1) in
  Printf.printf "(* Auto-generated by dune — do not edit *)\nlet s = %S\n"
    version
